# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Template' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Clean Architecture
  pod 'MGArchitecture', '~> 1.3.1'
  pod 'MGAPIService', '~> 2.2.1'
  pod 'MGLoadMore', '~> 1.3.1'
  
  # Rx
  pod 'NSObject+Rx', '~> 5.0'
  
  # Core
  pod 'ObjectMapper', '~> 3.5'
  pod 'Reusable', '~> 4.1'
  pod 'Then', '~> 2.4'
  pod 'Validator', '~> 3.2.1'
  
  # Others
  pod 'MBProgressHUD', '~> 1.2'
  pod 'SDWebImage', '~> 5.6'
  # Pods for RxSwift-Template
  
  target 'RxSwift-TemplateTests' do
  pod 'RxBlocking', '~> 5.1'
    inherit! :search_paths
    # Pods for testing
  end

end
