# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseMVVM-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseMVVM-C
pod 'Alamofire' 
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
end
